---
apiVersion: v1
kind: Pod
metadata: 
  name: nop-db
  labels: 
    app: nop 
spec: 
  containers: 
    - name: postgress
      image: postgres:16
      env:
        - name: POSTGRES_PASSWORD
          value: devops
        - name: POSTGRES_USER
          value: ganesh
        - name: POSTGRES_DB
          value: nop-postgress
      volumeMounts:
        - name: nop-vol
          mountPath: /var/lib/postgresql/data    
      resources:
        limits:
          cpu: 512Mi
          memory: 1000m 
  volumes:
    - name: nop-vol
      persistentVolumeClaim:
        claimName: nop-pvc
           

             
          
