---
apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: spc
  labels: 
    env: dev
    topic: replicaset
spec:
  minReadySeconds: 3
  replicas: 3
  selector:
    matchLabels:
      app: spc
  template: 
    metadata: 
      labels: 
        app: spc
        env: dev
        topic: pod
    spec: 
      containers:
        - name: spc
          image: springcommunity/spring-framework-petclinic:6.1.2
          ports:
            - containerPort: 8080
          resources:
            limits:
              memory: "128Mi" 
              cpu: "250m"   