---
apiVersion: v1
kind: Pod
metadata:
  name: mysql-pod
  labels:
    app: db
spec:
  containers:
    - name: nopdb
      image: mysql:8.0-debian
      env:
        - name: MYSQL_ROOT_PASSWORD
          value: admin123
        - name: MYSQL_DATABASE
          value: nop
        - name: MYSQL_USER
          value: ltdevops
        - name: MYSQL_PASSWORD
          value: admin123
      resources:
        limits:
          memory: 512Mi
          cpu: 1000m
      volumeMounts:
        - name: nop-vol
          mountPath: /var/lib/mysql
  volumes:
    - name: nop-vol
      persistentVolumeClaim: 
        claimName: nop-pvc