---
apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: be-rs
  labels:
    app: be
    topic: rs
spec:
  minReadySeconds: 2
  replicas: 2
  selector:
    matchExpressions:
      - key: app
        operator: In
        values:
          - be
  template:
    metadata:
      labels:
        app: be
        topic: pod
    spec:
      containers:
        - name: be-cont
          image: nginx
          ports:
            - containerPort: 80