---
apiVersion: v1
kind: Pod
metadata:
  name: filemount
spec:
  containers:
    - name: experiment
      image: alphine
      args:
        - sleep
        - 1d
      volumeMounts:  
        name: configvolume
        mountPath: /config
  volumes: 
    - name: configvolume
      configMap:
        name: nop-cm
