---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: skate-deploy
spec:
  minReadySeconds: 2
  replicas: 1
  selector:
    matchLabels:
      app: skate
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
  template:
    metadata:
      labels:
        app: skate
        version: v2.0
    spec:
      containers:
        - name: skate
          image: ganesh231/skateboard:1.0
          resources:
            limits:
              cpu: 250m
              memory: 128Mi
          ports:
            - containerPort: 80
              protocol: "TCP"
          readinessProbe:
            initialDelaySeconds: 3   ##  Wait 3 seconds after the container starts before checking readiness
            periodSeconds: 5         ## Check readiness every 5 seconds after the initial delay
            successThreshold: 3      ## Require 3 successful probes to mark the container as ready
            failureThreshold: 2      ## Require 2 failed probes to mark the container as unready
            httpGet:
              path: '/'              ## path: '/' means that Kubernetes will send a GET request to the root URL (e.g., http://<container-ip>:80/). You can change this to any endpoint that is designed to check the health of your service (e.g., /health or /status).
              port: 80

---
apiVersion: v1
kind: Service
metadata:
  name: skate-svc
spec:
  selector:
    app: skate
  ports:
    - port: 80
      targetPort: 80
      protocol: TCP