---
apiVersion: v1
kind: Pod
metadata:
  name: nodelabelpod
  spec:
    containers:
      - name: hello-container
        image: nginx:latest
        ports:
          - containerPort: 80
    nodeSelector:
      env: dev